title: Components
email: loeschef@janelia.hhmi.org
description: >-
  Some 3D printing, laser cutting, PCBs used in the Reiser lab at Janelia.

repository: reiserlab/Component-Designs

# Build settings
remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: "components"

kramdown:
  toc_levels: "1,2"


# change location of data directory from /_data to /assets/data
data_dir: assets/data

gh_edit_link: true
gh_edit_link_text: "🖊"
gh_edit_repository: "https://github.com/reiserlab/Component-Designs"
gh_edit_branch: "main"
gh_edit_view_mode: "edit" 
